### PR TITLE
Adds types

### LINKED ISSUE #1: Add `py.typed`
It looks like most of the library already has types. It'd probably be a fairly small effort to run mypy against the package and create a release with a `py.typed` file included.

Thoughts?

### PR DESCRIPTION
**Pull request by mfulgo**
Drops support for python 3.5 and adds mypy for type checking.

Also adds a GitHub Action for enforcing mypy checks in PRs.

Closes #1

### CODE REVIEW

**Comment by mfulgo** [comment]
I didn't add enforcement of formatting using black, because it looks like support for tabs was an issue...

Also, given that it drops support for a python version, you might want to make this release a major version bump. (Or not, since 3.5 and 3.6 are EOL, up to you! 🤷 )

**Comment by mfulgo** [comment]
@jleclanche - Any questions for me on this PR?

**Comment by jleclanche** [comment]
Thanks - But the `poetry.lock` file should not be committed to libraries. I'm landing this manually.

**Comment by jleclanche** [comment]
Landed in 5c65a9f

**Comment by mfulgo** [comment]
Awesome, thanks!

**Comment by jleclanche** [comment]
1.2.0 is released with your changes. Thank you :)

**Pull request closed without merging**
